name: ghidra
title: ghidra
summary: Ghidra SRE Tools
description: |
  A software reverse engineering (SRE) suite of tools developed by NSA's
  Research Directorate in support of the Cybersecurity mission
website: https://ghidra-sre.org/
contact: https://github.com/NationalSecurityAgency/ghidra/issues
issues: https://github.com/NationalSecurityAgency/ghidra/issues
source-code: https://github.com/NationalSecurityAgency/ghidra
license: Apache-2.0
icon: snap/gui/ghidra.png
adopt-info: ghidra

base: core22
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  ghidra:
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-$CRAFT_ARCH_BUILD_FOR
      PATH: $JAVA_HOME/bin:$PATH
      _JAVA_OPTIONS: -Duser.home="$SNAP_USER_COMMON" -Djavax.net.ssl.trustStore=/snap/gradle/current/etc/ssl/certs/java/cacerts
    command: ghidra/ghidraRun
    plugs:
    - desktop
    - home
    - network-bind
    - x11

  analyzeHeadless:
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-$CRAFT_ARCH_BUILD_FOR
      PATH: $JAVA_HOME/bin:$PATH
      _JAVA_OPTIONS: -Duser.home="$SNAP_USER_COMMON" -Djavax.net.ssl.trustStore=/snap/gradle/current/etc/ssl/certs/java/cacerts
    command: ghidra/support/analyzeHeadless
    plugs:
    - desktop
    - home
    - network-bind
    - x11 # Still required even for headless operation

parts:
  ghidra:
    plugin: nil
    source: https://github.com/NationalSecurityAgency/ghidra.git
    source-tag: stable
    build-environment:
      - _JAVA_OPTIONS: -Djavax.net.ssl.trustStore=/snap/gradle/current/etc/ssl/certs/java/cacerts
    stage-packages:
      - openjdk-21-jdk
      - ca-certificates-java
    build-packages:
      - unzip
    build-snaps:
      - gradle/latest/edge
    override-pull: |
      craftctl default

      version_file=Ghidra/application.properties
      version=$(sed -n "s/application.version=\(.*\)\+/\1/p" $version_file)

      craftctl set version="$version"
    override-build: |
      craftctl default

      gradle -I gradle/support/fetchDependencies.gradle
      gradle buildGhidra -PallPlatforms

      unzip -d $CRAFT_PART_INSTALL build/dist/ghidra_*.zip
      mv $CRAFT_PART_INSTALL/ghidra_* $CRAFT_PART_INSTALL/ghidra
    prime:
      - -usr/lib/jvm/java-21-openjdk-*/lib/security/blacklisted.certs
